### ISSUE TITLE
Examples in readme is misleading

### ISSUE THREAD

**Issue by vodolaz095** [Jsonize/js-ffmpeg#10]
I try to execute this code

```
         return new Promise(function (resolve, reject) {
            ffmpeg.ffmpeg(
              pathToTempFile, // input
              { // params
                width: 360,
                height: 360,
                auto_rotate: true,
                ratio_strategy: 'fixed',
                shrink_strategy: 'crop',
                mixed_strategy: 'crop-pad',
                stretch_strategy: 'pad'
              },
              path.join(os.tmpdir(), `video360_${task.id}.mp4`), // output
              function (progress) { // progress tracker
                logger.silly('ProcessVideo: Progress', progress);
              })
              .success(resolve)
              .error(function (error){
                console.error(error);
                reject(error);
              });
```

and i get this error output

```
debug: ProcessVideo: Generating 360p video...
{
  message: '[object: Invalid argument',
  logs: 'ffmpeg version 4.2.4 Copyright (c) 2000-2020 the FFmpeg developers\n' +
    '  built with gcc 10 (GCC)\n' +
    "  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --docdir=/usr/share/doc/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' --extra-ldflags='-Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld ' --extra-cflags=' ' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --disable-crystalhd --enable-fontconfig --enable-frei0r --enable-gcrypt --enable-gnutls --enable-ladspa --enable-libaom --enable-libdav1d --enable-libass --enable-libbluray --enable-libcdio --enable-libdrm --enable-libjack --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-nvenc --enable-openal --enable-opencl --enable-opengl --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-libsrt --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-version3 --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-libxml2 --enable-libzimg --enable-libzvbi --enable-lv2 --enable-avfilter --enable-avresample --enable-libmodplug --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-libmfx --enable-runtime-cpudetect\n" +
    '  libavutil      56. 31.100 / 56. 31.100\n' +
    '  libavcodec     58. 54.100 / 58. 54.100\n' +
    '  libavformat    58. 29.100 / 58. 29.100\n' +
    '  libavdevice    58.  8.100 / 58.  8.100\n' +
    '  libavfilter     7. 57.100 /  7. 57.100\n' +
    '  libavresample   4.  0.  0 /  4.  0.  0\n' +
    '  libswscale      5.  5.100 /  5.  5.100\n' +
    '  libswresample   3.  5.100 /  3.  5.100\n' +
    '  libpostproc    55.  5.100 / 55.  5.100\n' +
    '[lrc @ 0x563bfec28e40] Format lrc detected only with low score of 5, misdetection possible!\n' +
    "Input #0, lrc, from '/tmp/61420f1094e736ef4d2c0fa3b8589aef':\n" +
    '  Duration: N/A, bitrate: N/A\n' +
    '    Stream #0:0: Subtitle: text\n' +
    "[NULL @ 0x563bfec2d400] Unable to find a suitable output format for '[object'\n" +
    '[object: Invalid argument\n' +
    'undefined',
  command: '-i /tmp/61420f1094e736ef4d2c0fa3b8589aef [object Object] -y /tmp/video360_32.mp4'
}

[object: Invalid argument
```

I think its because parameters object is not accepted in code.

What am i doing wrong?

**Comment by ntshcalleia** [comment]
Hi @vodolaz095, it looks like there's a typo on the readme. 😬 Can you try using `ffmpeg.ffmpeg_simple` instead of `ffmpeg.ffmpeg`? The `ffmpeg.ffmpeg` command expects an array instead of object for the options.

**Comment by vodolaz095** [comment]
thanks for prompt reply.

i executed function this way:

```javascript
          return new Promise(function (resolve, reject) {
            ffmpeg.ffmpeg_simple(
              pathToTempFile, // input
              { // params
                width: 360,
                height: 360,
                auto_rotate: true,
                ratio_strategy: 'fixed',
                shrink_strategy: 'crop',
                mixed_strategy: 'crop-pad',
                stretch_strategy: 'pad'
              },
              path.join(os.tmpdir(), `video360_${task.id}.mp4`), // output
              function (progress) { // progress tracker
                logger.silly('ProcessVideo: Progress', progress);
              })
              .success(resolve)
              .error(function (error){
                logger.error(error);
                reject(error);
              });
          });
```


and i have received quite big error stacktrace:

```
TypeError: Cannot read property 'rotation' of undefined
    at Promise.<anonymous> (/home/projects/vodolaz095/lingvano_backend/node_modules/js-ffmpeg/src/ffmpeg-simple.js:188:55)
    at Promise.<anonymous> (/home/projects/vodolaz095/lingvano_backend/node_modules/betajs/dist/beta.js:13396:39)
    at Promise.triggerResult (/home/projects/vodolaz095/lingvano_backend/node_modules/betajs/dist/beta.js:13220:33)
    at Promise.triggerResult (/home/projects/vodolaz095/lingvano_backend/node_modules/betajs/dist/beta.js:13229:26)
    at Promise.asyncSuccess (/home/projects/vodolaz095/lingvano_backend/node_modules/betajs/dist/beta.js:13293:25)
    at Promise.promise.results (/home/projects/vodolaz095/lingvano_backend/node_modules/betajs/dist/beta.js:12878:26)
    at Object.f (/home/projects/vodolaz095/lingvano_backend/node_modules/betajs/dist/beta.js:12846:34)
error    at Promise.triggerResult (/home/projects/vodolaz095/lingvano_backend/node_modules/betajs/dist/beta.js:13224:33)
: undefined
    at Promise.triggerResult (/home/projects/vodolaz095/lingvano_backend/node_modules/betajs/dist/beta.js:13229:26)
    at Promise.asyncSuccess (/home/projects/vodolaz095/lingvano_backend/node_modules/betajs/dist/beta.js:13293:25)
    at Promise.<anonymous> (/home/projects/vodolaz095/lingvano_backend/node_modules/betajs/dist/beta.js:13400:33)
    at Promise.triggerResult (/home/projects/vodolaz095/lingvano_backend/node_modules/betajs/dist/beta.js:13220:33)
    at Promise.triggerResult (/home/projects/vodolaz095/lingvano_backend/node_modules/betajs/dist/beta.js:13229:26)
    at Promise.asyncSuccess (/home/projects/vodolaz095/lingvano_backend/node_modules/betajs/dist/beta.js:13293:25)
    at ChildProcess.<anonymous> (/home/projects/vodolaz095/lingvano_backend/node_modules/js-ffmpeg/src/ffprobe.js:42:29)
    at ChildProcess.emit (events.js:314:20)
    at ChildProcess.EventEmitter.emit (domain.js:483:12)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)

TypeError: Cannot read property 'rotation' of undefined
    at Promise.<anonymous> (node_modules/js-ffmpeg/src/ffmpeg-simple.js:188:55)
    at Promise.<anonymous> (node_modules/betajs/dist/beta.js:13396:39)
    at Promise.triggerResult (node_modules/betajs/dist/beta.js:13220:33)
    at Promise.triggerResult (node_modules/betajs/dist/beta.js:13229:26)
    at Promise.asyncSuccess (node_modules/betajs/dist/beta.js:13293:25)
    at Promise.promise.results (node_modules/betajs/dist/beta.js:12878:26)
    at Object.f (node_modules/betajs/dist/beta.js:12846:34)
    at Promise.triggerResult (node_modules/betajs/dist/beta.js:13224:33)
    at Promise.triggerResult (node_modules/betajs/dist/beta.js:13229:26)
    at Promise.asyncSuccess (node_modules/betajs/dist/beta.js:13293:25)
    at Promise.<anonymous> (node_modules/betajs/dist/beta.js:13400:33)
    at Promise.triggerResult (node_modules/betajs/dist/beta.js:13220:33)
    at Promise.triggerResult (node_modules/betajs/dist/beta.js:13229:26)
    at Promise.asyncSuccess (node_modules/betajs/dist/beta.js:13293:25)
    at ChildProcess.<anonymous> (node_modules/js-ffmpeg/src/ffprobe.js:42:29)
    at ChildProcess.EventEmitter.emit (domain.js:483:12)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)

```

**Comment by vodolaz095** [comment]
seems like this code gives error
https://github.com/Jsonize/js-ffmpeg/blob/master/src/ffmpeg-simple.js#L188

**Comment by vodolaz095** [comment]
its worth notice that video file i'm processing doesn't include audio, probably it makes issues...

**Comment by vodolaz095** [comment]
i invoked function this way

```
          return new Promise(function (resolve, reject) {
            ffmpeg.ffmpeg_simple(
              pathToTempFile, // input
              { // params
                width: 360,
                height: 360,
              },
              path.join(os.tmpdir(), `video360_${task.id}.mp4`), // output
              function (progress) { // progress tracker
                logger.silly('ProcessVideo: Progress', progress);
              })
              .success(resolve)
              .error(function (error){
                logger.error(error);
                reject(error);
              });
          });
```


i left only final resulotion as options, and i recieve same stacktrace like here https://github.com/Jsonize/js-ffmpeg/issues/10#issuecomment-883419569

**Comment by ntshcalleia** [comment]
Thanks for providing more information, I'll try to reproduce it. Does it work when you set `auto_rotate` to false?
